### ISSUE TITLE
Template - MS SQL Server Select to CSV file

### ISSUE THREAD

**Issue by jefim** [FrendsPlatform/FrendsTemplates#2]
Takes the result of MS SQL Server Select and generates a CSV file

Will probably be SFTP to send CSV file to a specific server address. SQL will need to be generic

- MSSQL - Azure
- Save CSV locally

**Comment by davegroberts** [comment]
Attaching design doc
[Template - MS SQL Server DB Select to CSV file.docx](https://github.com/FrendsPlatform/FrendsTemplates/files/14296107/Template.-.MS.SQL.Server.DB.Select.to.CSV.file.docx)

**Comment by davegroberts** [comment]
Attaching design docs for basic error handler
[Template – Generic Error Handler (no limit).docx](https://github.com/FrendsPlatform/FrendsTemplates/files/14296121/Template.Generic.Error.Handler.no.limit.docx)
[Template – Generic Error Handler (limited notifications).docx](https://github.com/FrendsPlatform/FrendsTemplates/files/14296123/Template.Generic.Error.Handler.limited.notifications.docx)

**Comment by jefim** [comment]
Need docs and PR according to new guidelines
