### ISSUE TITLE
Template - Json file to  MS SQL Server DB Insert

### ISSUE THREAD

**Issue by jefim** [FrendsPlatform/FrendsTemplates#3]
Takes the contents of a Json file and generates a MS SQL Server insert statement

Will probably be SFTP access to get text file. SQL will need to be generic

- SFTP from Azure Blob Storage
- MSSQL from Azure

**Comment by davegroberts** [comment]
Attaching design doc
[Template - Json file to MS SQL Server DB Insert.docx](https://github.com/FrendsPlatform/FrendsTemplates/files/14296100/Template.-.Json.file.to.MS.SQL.Server.DB.Insert.docx)

**Comment by jefim** [comment]
Need docs and PR according to new guidelines
