### ISSUE TITLE
Template - JSON file to CSV file

### ISSUE THREAD

**Issue by jefim** [FrendsPlatform/FrendsTemplates#4]
Takes the contents of a Json file and generates a CSV file

Will probably be SFTP access to get Json file and to send CSV file to a specific server address. Will need to flatten the Json structure for the Json To CSV task to work correctly.

- SFTP from Azure Blob Storage
- Save CSV locally

**Comment by davegroberts** [comment]
Add design document
[Template - Json file to CSV file.docx](https://github.com/FrendsPlatform/FrendsTemplates/files/14373152/Template.-.Json.file.to.CSV.file.docx)

**Comment by davegroberts** [comment]
Here's some code I wrote a while back for flattening Json
{
    JObject tmpusr = JObject.Parse(#var.dataEntry.ToString());
    IEnumerable<JToken> jTokens = tmpusr.Descendants().Where(p => !p.HasValues);
    Dictionary<string, string> results = jTokens.Aggregate(new Dictionary<string, string>(), (properties, jToken) =>
                    {
                        properties.Add(jToken.Path, jToken.ToString());
                        return properties;
                    });

    #var.data.Add(JObject.FromObject(results));
}

**Comment by ttossavainen** [comment]
Done.

**Comment by jefim** [comment]
This needs to be re-reviewed and docs written according to new guidelines
