### ISSUE TITLE
Generic Order file to Saleforce

### ISSUE THREAD

**Issue by jefim** [FrendsPlatform/FrendsTemplates#59]

**Comment by davegroberts** [comment]
Design document
https://unthink.sharepoint.com/:w:/r/sites/frendsdemoteam/Shared%20Documents/General/Templates/Design%20Documents/Generic%20CSV%20Order%20File%20to%20SalesForce%20-%20Order.docx?d=wdcd70a00fbda410eaf0ea724fd16e03f&csf=1&web=1&e=1KhFfz
