### ISSUE TITLE
Adobe Commerce (Magento) to Salesforce - Invoices

### ISSUE THREAD

**Issue by jefim** [FrendsPlatform/FrendsTemplates#60]

**Comment by davegroberts** [comment]
Design document
https://unthink.sharepoint.com/:w:/r/sites/frendsdemoteam/Shared%20Documents/General/Templates/Design%20Documents/Adobe%20Commerce%20(Magento)%20REST%20API%20to%20SalesForce%20-%20Invoice.docx?d=w0497820e4a4d4a6fa14ff818d6fb0dba&csf=1&web=1&e=fcUjCi

**Comment by jefim** [comment]
Salesforce does not allow creating invoices easily, shelf this until further notice.
