### ISSUE TITLE
Adobe Commerce (Magento) REST API to Salesforce - Order

### ISSUE THREAD

**Issue by jefim** [FrendsPlatform/FrendsTemplates#61]

**Comment by davegroberts** [comment]
Design document
https://unthink.sharepoint.com/:w:/r/sites/frendsdemoteam/Shared%20Documents/General/Templates/Design%20Documents/Adobe%20Commerce%20(Magento)%20REST%20API%20to%20SalesForce%20-%20Order.docx?d=wf919d987e646437abb697bb61f381879&csf=1&web=1&e=b015Dx
