### ISSUE TITLE
Adobe Commerce (Magento) REST API to Salesforce - Customer

### ISSUE THREAD

**Issue by jefim** [FrendsPlatform/FrendsTemplates#62]

**Comment by davegroberts** [comment]
Design document
https://unthink.sharepoint.com/:w:/r/sites/frendsdemoteam/Shared%20Documents/General/Templates/Design%20Documents/Adobe%20Commerce%20(Magento)%20REST%20API%20to%20SalesForce%20-%20Customer.docx?d=wae75fb4c526944ec9632f5400f8aaba1&csf=1&web=1&e=UtlyBj
