### ISSUE TITLE
Template - CSV file to MS SQL DB Insert

### ISSUE THREAD

**Issue by ttossavainen** [FrendsPlatform/FrendsTemplates#7]

**Comment by davegroberts** [comment]
Design Document Added
[Template - Json file to MS SQL Server DB Insert.docx](https://github.com/FrendsPlatform/FrendsTemplates/files/14663011/Template.-.Json.file.to.MS.SQL.Server.DB.Insert.docx)

**Comment by jefim** [comment]
See https://templates-dev.frendsapp.com/Process/Edit/821
